# Generated by Django 3.1.4 on 2022-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermonattendance',
            name='children',
        ),
        migrations.RemoveField(
            model_name='sermonattendance',
            name='female',
        ),
        migrations.RemoveField(
            model_name='sermonattendance',
            name='male',
        ),
        migrations.AddField(
            model_name='sermonattendance',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermonattendance',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermonattendance',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermonattendance',
            name='video',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
