# Generated by Django 3.1.4 on 2022-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221110_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermonattendance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sermonattendance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sermonattendance',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sermonattendance',
            name='video',
        ),
        migrations.AddField(
            model_name='sermonattendance',
            name='children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermonattendance',
            name='female',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermonattendance',
            name='male',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
