# Generated by Django 3.1.4 on 2022-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221110_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermonattendance',
            name='count_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
