# Generated by Django 3.1.4 on 2022-11-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221111_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('someabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.someabstractmodel')),
                ('Title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            bases=('home.someabstractmodel',),
        ),
    ]
