# Generated by Django 3.1.4 on 2022-11-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221112_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeeds',
            name='picture',
        ),
    ]
