# Generated by Django 3.1.4 on 2022-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_newsfeeds_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeeds',
            name='picture',
            field=models.ImageField(default='posts/img/IMG-20221023-WA0005', upload_to='posts/img'),
            preserve_default=False,
        ),
    ]
