# Generated by Django 3.1.4 on 2022-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_album_audiosermon'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosermon',
            name='file',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
    ]
