# Generated by Django 3.1.4 on 2022-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_audiosermon_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosermon',
            name='file',
            field=models.FileField(upload_to='musics'),
        ),
    ]
