# Generated by Django 3.1.4 on 2022-11-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221113_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosermon',
            name='file',
        ),
        migrations.AddField(
            model_name='audiosermon',
            name='afile',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
    ]
