# Generated by Django 3.1.4 on 2022-11-14 20:52

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221113_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosermon',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='your/upload/dir'),
        ),
    ]
